enabled_features:
  video: True
  video_undistort: False
  gps: True
  imu: True
  canbus: True
  monitoring_panel: True

#camera_serial_numbers:
#  center: 50-0536957144
#  left: 50-0536955287
#  right: 50-0536957147

camera_ids:
  center: DEV_000F315CDD58
  left: DEV_000F315CDD5B
  right: DEV_000F315CD617

video_resolution:
  width: 2064
  height: 1544

gps_port: /dev/ttyACM0
imu_port: /dev/ttyACM1

can_device: slcan0
can_dbc_file: logan.dbc

network_streaming:
  host: 0.0.0.0
  port: 6366
  sync_manager_host: 0.0.0.0
  sync_manager_port: 8986
  header_size: 10
  recv_buffer: 104857600
