enabled_features:
  video: True
  video_undistort: False
  gps: False
  imu: True
  monitoring_panel: True

#camera_serial_numbers:
#  center: 50-0536957144
#  left: 50-0536955287
#  right: 50-0536957147

camera_ids:
  center: DEV_000F315CDD58
  left: DEV_000F315CD617
  right: DEV_000F315CDD5B

camera_auto_features:
  auto_adjust_packet_size: True
  auto_exposure: False
  auto_white_balance: False
  auto_iso: False

gps_port: /dev/ttyACM1
imu_port: /dev/ttyACM0

can_device: vcan0
can_dbc_file: logan.dbc

car_data_server:
  host: 0.0.0.0
  port: 6366
  header_size: 10
