enabled_features:
  video: True
  video_undistort: False
  gps: False
  imu: False
  monitoring_panel: True

camera_serial_numbers:
  center: 50-0536957144
  left: 50-0536955287
  right: 50-0536957147

camera_auto_features:
  auto_adjust_packet_size: True
  auto_exposure: False
  auto_white_balance: False
  auto_iso: False

gps_port: COM7

car_data_server:
  host: 0.0.0.0
  port: 6366
  header_size: 10
